### ISSUE TITLE
Converting the tiff from local directory into EO-Patches 

### ISSUE THREAD

**Issue by spaceie07** [sentinel-hub/field_delineation#18]
I am trying to convert the raster tiffs that I have already downloaded into EO patches. The script seemed to be hard coded for AWS S3 bucket and Batch Processing API. 

There's certainly a way to convert the tiffs from local directory into EO patches but Im having a hard time to find it. 
Any help will be much appreciated.

**Comment by batic** [comment]
The `ImportFromTiffTask` is what you are after: https://eo-learn.readthedocs.io/en/latest/reference/eolearn.io.raster_io.html#eolearn.io.raster_io.ImportFromTiffTask

**Comment by spaceie07** [comment]
Thankyou for responding. 
I have been trying to implement this task through the following code:
```
from eolearn.io.local_io import ImportFromTiffTask
band= ImportFromTiffTask(feature='EoPatch' , folder='/content/S2B_tile_20220905_42RVQ_0_R10B03.TIF')
band.execute(eopatch=None,  filename=None)
```
The eopatch= None because I want to create a new EO patch rather than writing the features into an existing EO Patch, and it's giving me the following error:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/116105161/200308833-e2f25be1-c40e-486d-9520-da69aaf26116.png">


Can you please correct me where I might be making a mistake.

**Comment by batic** [comment]
Closing issue as the repository is being archived.
