### ISSUE TITLE
fb libary is not compatible with Python 3.x

### ISSUE THREAD

**Issue by bumie-e** [sentinel-hub/field_delineation#20]
While importing fb modules in a colab notebook,

`from fd.scripts.download import batch_download` gave this error

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-12-3a63f76ed967>", line 17, in <module>
    from fd.scripts.download import batch_download

  File "/usr/local/lib/python3.8/dist-packages/fd.py", line 53
    print "Directory or database already exists. Use -f or --force to delete and initialize"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Directory or database already exists. Use -f or --force to delete and initialize")?

The error shows that the print function is written in Python 2.x. How do I resolve this?

**Comment by devisperessutti** [comment]
Hi @bumie-e 

It looks like you installed the wrong `fd` package, possibly from `pypi`. 

Our code definitely works for Python 3.*.

To install our package you DON'T do `pip install fd`, but you have to first install the requirements and then the package, as shown in the README

```
pip install -r requirements.txt
python setup.py install --user
```

I suggest you create a new fresh Python environment, install field delineation and try again.

Let us know if it works.

**Comment by bumie-e** [comment]
Yes, using `pip install fd` was the issue. It works now, thanks!
