### ISSUE TITLE
No module named 'sentinelhub.os_utils'

### ISSUE THREAD

**Issue by pganot2** [sentinel-hub/field_delineation#22]
I have installed the necessary libraries by following the instructions. 
However, when I get to the `from eolearn.core import EOPatch` I am getting the following ModulNotFoundError:
![image](https://github.com/sentinel-hub/field-delineation/assets/73099341/4a1de982-0efc-4a79-91f1-5a01d4db2d45)

I am not sure why this is happening, but it just means something isn't being downloaded correctly.

**Comment by batic** [comment]
Closing issue; with fixed package versions this should be resolved.
