### ISSUE TITLE
input_data

### ISSUE THREAD

**Issue by LucaScalam** [sentinel-hub/field_delineation#3]
Hi,

I can't find the input data. Can somebody give me a hand ?

Kinds Regards,
Luca Scalambrin

**Comment by batic** [comment]
Hi @LucaScalam,

Unfortunately, we cannot share the GSAA input data we've used. The objective of this repo is to show how we have approached the task at hand, using Sentinel Hub to retrieve satellite data.  

Perhaps you can try with your country (GSAA/LPIS) data?

**Comment by LucaScalam** [comment]
Yes, I'll try with that.

Thanks @batic !

**Comment by batic** [comment]
Good luck! Let us know how it goes.
