### ISSUE TITLE
Reflect recent changes in SentinelHubBatch interface

### ISSUE THREAD

**Issue by chase-dwelle** [sentinel-hub/field_delineation#9]
Recent changes to the `SentinelHubBatch` interface have broken functionality of the notebooks on new installs. 

https://github.com/sentinel-hub/sentinelhub-py/pull/208

**Comment by batic** [comment]
You are right. We will update the code in next days. In the meantime, please use older sh-py versions (e.g. https://github.com/sentinel-hub/sentinelhub-py/releases/tag/v3.3.2 or older).

**Comment by batic** [comment]
Closing issue, things should work with fixed packages.
